### PR TITLE
Add button to rename links.

### PR DESCRIPTION
**Pull request by stevennoto**
Hi again @kevinwucodes! While I was doing #41 I figured it wouldn't be too hard to allow renaming quick links, which I would find super useful, so here it is.

I added a rename button with an icon:
link-rename-button

This pops open a prompt to rename the link:
link-rename-popup

Let me know if you like [the icon I chose](https://icons8.com/icon/57888/edit-file) and the feature in general.

I think the next step would be to allow editing the link's urlHash too, but that might require a custom JS popup which would be a bigger thing to add.

Thanks!

### CODE REVIEW

**Comment by kevinwucodes** [comment]
@stevennoto, this looks GREAT!!!  I love this!

I have one small minor suggestion.  I'm using a dark theme (white text on black background) and the black edit-file icon is a bit hard to see.  Maybe there's another edit-file type icon that has a different stroke color other than black?  I see that you're using a blue background color so whatever color is chosen, someone's background color will drown out the selected stroke color.

**Comment by stevennoto** [comment]
Thanks for the feedback. I see your point. I tried a few icons to find one that would be recognizable at that size. What do you think about a pencil icon yellow maybe, like https://icons8.com/icon/20388/pencil-drawing? Or maybe one of these? https://icons8.com/icons/set/rename

**Comment by kevinwucodes** [comment]
Lets do a yellow pencil!

**Comment by stevennoto** [comment]
See how this one works. I tried it in a few themes and it'd decent with a white and a black background.

**Pull request merged**
